

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.11"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/spf13/cast"
  version = "1.3.0"

[[constraint]]
  name = "gitlab.com/tokend/go"
  version = "3.8.0"

[[constraint]]
  name = "gitlab.com/tokend/horizon-connector"
  version = "4"

[prune]
  go-tests = true
  unused-packages = true
