

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.11"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/spf13/cast"
  version = "1.3.0"

[[override]]
  name = "gitlab.com/tokend/go"
  branch = "keys"

[[override]]
  name = "gitlab.com/tokend/regources"
  branch = "keys"

[prune]
  go-tests = true
  unused-packages = true
